### ISSUE TITLE
PropTypes snippets

### ISSUE THREAD

**Issue by frontcraft** [burkeholland/simple-react-snippets#10]
It would be good to have a snippets for defining proptypes. Check the following example. I used "|" as a placeholder for cursor.

after typing **pt**:
```
|.propTypes = {
  |: PropTypes.|,
}
```
after typing **dp**:
```
|.defaultProps = {
  |,
};
```

**Comment by burkeholland** [comment]
I'm _super_ hesitant to include PropTypes snippets because they are going to clutter up the command palette in a hurry. The options when working with PropTypes can [balloon pretty quickly](https://reactjs.org/docs/typechecking-with-proptypes.html). Do you think a simple snippet like the one you are proposing would suffice?

Also, PropTypes is now in a separate library from React. Should React PropTypes be it's own extension?

**Comment by ajayns** [comment]
@burkeholland I agree, it'd bloat things up real quick cause there'd be plenty of options to consider then. Again I agree that React PropTypes should be a separate extension by itself. The prime feature for which I like this extension is its utility and simplicity.

**Comment by burkeholland** [comment]
I'm going to close for now. Not because it isn't a great idea, but because I think it's just not the right idea for this particular extension. Maybe someone could get to work on Simple PropTypes. 😀
